# Generated by Django 3.0.3 on 2022-02-12 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 52, 564215)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 52, 565205)),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 52, 567202)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 52, 562221)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 12, 12, 43, 52, 561216)),
        ),
    ]
