# Generated by Django 3.0.3 on 2022-02-12 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicifyapp', '0003_auto_20220212_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Facebook', max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 1, 41, 9, 437586)),
        ),
        migrations.AlterField(
            model_name='blogs_comments',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 1, 41, 9, 439582)),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 13, 1, 41, 9, 441577)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 13, 1, 41, 9, 434621)),
        ),
        migrations.AlterField(
            model_name='posted_jobs',
            name='post_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 13, 1, 41, 9, 433632)),
        ),
    ]
